external-controller: 127.0.0.1:9090
geodata-mode: true

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

load: &load
  type: load-balance
  use:
    - Remote
  url: 'https://www.gstatic.com/generate_204'
  interval: 300

proxy-providers:

  Remote:
    type: http  #支持机场通用订阅
    url: 'https://www.gstatic.com/generate_204'
    interval: 3600
    path: "./Providers/Proxy/Remote.yaml"
    health-check:
      enable: true
      interval: 1200
      url: https://gstatic.com/generate_204

        #Local:
        #type: file  #支持解析节点分享格式，新建并填写在Local.yaml即可
        #path: "./Providers/Proxy/Local.yaml"
        #health-check:
        #enable: true
        #interval: 1200
        #url: https://gstatic.com/generate_204

proxy-groups:

  - name: 🚀 节点选择
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🇺🇲 美国节点
      - 🌀 手动切换

  - name: 🌀 手动切换
    type: select
    use:
      - Remote

  - name: 🎥 奈飞视频
    type: select
    proxies:
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🌀 手动切换

  - name: 🍃 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: 🇭🇰 香港节点
    <<: *load
    filter: '香港'

  - name: 🇨🇳 台湾节点
    <<: *load
    filter: '台湾'

  - name: 🇸🇬 狮城节点
    <<: *load
    filter: '狮城|新加坡'

  - name: 🇯🇵 日本节点
    <<: *load
    filter: '日本'

  - name: 🇰🇷 韩国节点
    <<: *load
    filter: '韩国'

  - name: 🇺🇲 美国节点
    <<: *load
    filter: '美国'

rules:
  - GEOSITE,category-ads-all,🍃 广告拦截
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,🚀 节点选择
  - GEOIP,TELEGRAM,🚀 节点选择
  - GEOIP,NETFLIX,🎥 奈飞视频
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择
